import type { AvailableCoupon } from "@/actions/coupon";

/** Explicitly fictional examples for the isolated demo; no codes can be issued. */
export const demoBenefitsFixtures: AvailableCoupon[] = [
  {
    id: "demo-benefit-horizonte",
    slug: "taller-horizonte-demo",
    name: "Taller Horizonte",
    description: "Ejemplo ficticio de un beneficio para mostrar el flujo visual de la demo.",
    instagramHandle: "",
    instagramUrl: "",
    logoKey: null,
    rule: "ONCE_PER_USER",
    pendingCode: null,
    blocked: false,
    blockedReason: null,
    fixedCode: null,
    websiteUrl: null,
    restrictions: "Comercio y beneficio ficticios; no tienen validez comercial.",
  },
  {
    id: "demo-benefit-norte",
    slug: "club-norte-demo",
    name: "Club Norte",
    description: "Muestra ficticia de una alianza con regla de uso mensual, sin canje disponible.",
    instagramHandle: "",
    instagramUrl: "",
    logoKey: null,
    rule: "ONCE_PER_USER_PER_MONTH",
    pendingCode: null,
    blocked: false,
    blockedReason: null,
    fixedCode: null,
    websiteUrl: null,
    restrictions: "Contenido de demostración únicamente; no genera descuentos reales.",
  },
  {
    id: "demo-benefit-puente",
    slug: "espacio-puente-demo",
    name: "Espacio Puente",
    description: "Beneficio ficticio para representar una oferta de uso libre dentro de la interfaz.",
    instagramHandle: "",
    instagramUrl: "",
    logoKey: null,
    rule: "UNLIMITED",
    pendingCode: null,
    blocked: false,
    blockedReason: null,
    fixedCode: null,
    websiteUrl: null,
    restrictions: "Ejemplo sin comercio asociado, código, contacto ni promesa comercial.",
  },
];
